#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "sonarr-main";
	CREATE DATABASE "sonarr-log";
	GRANT ALL PRIVILEGES ON DATABASE "sonarr-main" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "sonarr-log" TO "$POSTGRES_USER";

	CREATE DATABASE "radarr-main";
	CREATE DATABASE "radarr-log";
	GRANT ALL PRIVILEGES ON DATABASE "radarr-main" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "radarr-log" TO "$POSTGRES_USER";

	CREATE DATABASE "prowlarr-main";
	CREATE DATABASE "prowlarr-log";
	GRANT ALL PRIVILEGES ON DATABASE "prowlarr-main" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "prowlarr-log" TO "$POSTGRES_USER";

	CREATE DATABASE "bazarr";
	GRANT ALL PRIVILEGES ON DATABASE "bazarr" TO "$POSTGRES_USER";
EOSQL
